### ISSUE TITLE
Error when running runner_motion.py

### ISSUE THREAD

**Issue by YiLin32Wang** [christsa/dgrasp#11]
Hi,

I'm running into an error about lib file when trying to run the runner_motion.py demo.

> Traceback (most recent call last):
  File "raisimGymTorch/env/envs/dgrasp/runner_motion.py", line 4, in <module>
    from raisimGymTorch.helper.raisim_gym_helper import ConfigurationSaver, load_param, tensorboard_launcher
  File "/home/datassd/yilin/Codes/Hand/dgrasp/raisimGymTorch/raisimGymTorch/helper/__init__.py", line 1, in <module>
    from .raisim_gym_helper import *
  File "/home/datassd/yilin/Codes/Hand/dgrasp/raisimGymTorch/raisimGymTorch/helper/raisim_gym_helper.py", line 5, in <module>
    import torch
  File "/home/yilin/anaconda3/envs/raisim/lib/python3.8/site-packages/torch-2.0.0-py3.8-linux-x86_64.egg/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcupti.so.11.7: cannot open shared object file: No such file or directory

and it seems that it's a predefined for CUDA 11.7, but my lib64 folder only contain libcupti.so.11.4 since the CUDA I'm using is 11.4.

Could this be fixed? Or is it a strong requirement of using CUDA 11.7 for this repo?

Thanks,
Yilin

**Comment by christsa** [comment]
Hi,

Could this be related to your torch installation?
D-Grasp does not depend on a specific version of torch as seen [here](https://github.com/christsa/dgrasp/blob/main/raisimGymTorch/setup.py#L78).
If your torch version is not compatible with your CUDA version, this error may occur.

**Comment by YiLin32Wang** [comment]
Hi,

Thanks for the instant reply!
I've changed to suitable pytorch version and it works. Thanks again!
